<chart>
windows_total=1
<expert>
name=Strategies\Gold_Predator_HF\Gold_Predator
path=Experts\Strategies\Gold_Predator_HF\Gold_Predator.ex5
expertmode=1
<inputs>
InpADXThreshold=34
InpTPMult=7.5
InpMomentumRatio=0.7
InpRiskPercent=2.0
InpSLMult=1.6
InpMagic=777777
</inputs>
</expert>
<window>
height=100
fixed_height=0
<indicator>
name=Main
<object>
type=102
name=PredatorBanner
font_name=Segoe UI
font_size=12
color=65535
anchor=0
angle=0.00
x_distance=20
y_distance=20
hidden=1
editable=0
tooltip=Gold Predator HF Active (ADX 34 Golden Standard)
</object>
</indicator>
</window>
</chart>
