<chart>
windows_total=1
<expert>
name=Strategies\Rev_Bollinger\Rev_Bollinger
path=Experts\Strategies\Rev_Bollinger\Rev_Bollinger.ex5
expertmode=1
<inputs>
InpMagicNumber=10101
InpRiskPercent=2.0
</inputs>
</expert>
<window>
<indicator>
name=Main
</indicator>
</window>
</chart>
